### ISSUE TITLE
DB Configuration

### ISSUE THREAD

**Issue by party98** [techspaceusict/infox18#6]
As can be verified by simply executing the code, the file `config/db.js` hasn't been committed and thus the app ceases to run.
Furthermore, given the kind of tabular data, it would be preferred that a SQL database is used as opposed to NoSQL (Mongo) as the data is tabular and consistent in format and a SQL database will be more suitable for the application and will also allow to segregate permissions allowing us to give limited access to coordinators of various events.

**Comment by shubhamg931** [comment]
It has been resolved. :)
